---
ssh_key_name: ""
target_dns_zone: ""
target_subdomain: ""
instance_name: ""
instance_lookup_value: ""

#aws_tag_prefix is used to name the various VPC resources so they are only created once per account
#even if shared with multiple IAM users
aws_tag_prefix: "test_awsdemo"

##
# us-east-1
##
aws_region: us-east-1
aws_ami_id: ami-b63769a1

##
# us-east-2
##
#aws_region: us-east-2
#aws_ami_id: ami-0932686c

instance_type: c4.2xlarge

openshift_hostname: "{{target_subdomain}}.{{target_dns_zone}}"
openshift_url: "{{ openshift_hostname }}:8443"

use_ssl: True
email_address: "foo@bar.com"

var_lib_docker_ebs_device_name: "sdc"
var_lib_docker_block_device: "/dev/xvdc"
var_lib_docker_mount_point: "/var/lib/docker"

docker_vg_ebs_device_name: "sdd"
docker_vg_block_device: "/dev/xvdd"
docker_vg_name: "docker_vg"

persistedvol_ebs_device_name: "sde"
persistedvol_block_device: "/dev/xvde"
persistedvol_mount_point: "/persistedvolumes"

tmp_ebs_device_name: "sdf"
tmp_block_device: "/dev/xvdf"
tmp_mount_point: "/tmp"


cluster_user: admin
cluster_user_password: admin
cluster_system_admin: "system:admin"
service_catalog_user: "system:serviceaccount:service-catalog:default"

oc_client_install_path: "/usr/local/bin"
oc_cmd: "{{ oc_client_install_path }}/oc"
oadm_cmd: "{{ oc_client_install_path }}/oadm"
kubectl_cmd: "{{ oc_client_install_path }}/kubectl"


dockerhub_user_name: "foo"
dockerhub_user_password: "foo"


aws_sec_group_name: "{{ aws_tag_prefix }}_security_group"
vpc_name: "{{ aws_tag_prefix }}_vpc"
vpc_cidr_block: "10.0.0.0/16"
vpc_subnet_a_cidr: "10.0.0.0/24"
vpc_subnet_a_name: "{{ aws_tag_prefix }}_subnet_a"
vpc_subnet_b_cidr: "10.0.1.0/24"
vpc_subnet_b_name: "{{ aws_tag_prefix }}_subnet_b"
vpc_route_table_name: "{{ aws_tag_prefix }}_route_table"
rds_subnet_group_name: "{{ aws_tag_prefix }}_rds_group"
